# -----------------------------------------------------------------------
# Trivadis AG, Business Development & Support (BDS)
# Saegereistrasse 29, 8152 Glattbrugg, Switzerland
# -----------------------------------------------------------------------
# Name.......: docker-compose.yml
# Author.....: Stefan Oehrli (oes) stefan.oehrli@trivadis.com
# Editor.....: Stefan Oehrli
# Date.......: 2019.01.17
# Revision...: --
# Purpose....: Simple compose file to create an Ora repository based on Busybox
# Notes......: --
#
# Reference..: https://github.com/oehrlis/oudbase
# License....: GPL-3.0+
# -----------------------------------------------------------------------
# Modified...:
# see git revision history with git log for more information on changes
# -----------------------------------------------------------------------
version: '3'
services:
  orarepo:
    image: busybox
    container_name: orarepo
    hostname: orarepo
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - /u00/app/oracle/software:/www
    ports:
      - "80:80"
    command: httpd -fvvv -h /www
# - EOF -----------------------------------------------------------------